### ISSUE TITLE
Need an option to resize the lens

### ISSUE THREAD

**Issue by yaser-ali-vp** [ethanselzer/react-image-magnify#21]
I need an option to resize the lens so that I can use a square lens or can change the dimensions of the lens.

**Comment by ethanselzer** [comment]
Hi @yaser-ali-vp - Thanks for opening this issue. When you use the word "lens", do you mean the enlarged image or the gray translucent overlay on the small image?

**Comment by yaser-ali-vp** [comment]
Hi @ethanselzer I mean the gray translucent overlay on the small image.

**Comment by ethanselzer** [comment]
@yaser-ali-vp - Thanks for the information. At this time the lens dimensions are not configurable. The lens on the small image is sized proportional to the area of the large image being displayed. If you use a square image, you will have a square lens. If you have a bigger large image you will have a smaller lens.

**Comment by ethanselzer** [comment]
@yaser-ali-vp - I'm not sure if [v2.5.0](https://github.com/ethanselzer/react-image-magnify/releases/tag/v2.5.0) helps your use case, but it might. Please have a look. Thanks.

**Comment by carlgunderson** [comment]
Hi @ethanselzer, thanks for maintaining this plugin!

Slightly related - is there a way to customize the display of the selected region, similar to <a href="https://smile.amazon.com/Bosch-GXL12V-310B22-3-Tool-Reciprocating-Worklight/dp/B0771YRK4X/">how Amazon does it</a>?

I think the effect looks better when you style the overlay of the active portion, rather than over the rest of the image. But, I can't seem to find any way to target that guy. Originally, I thought the `lensStyle` would've done it, but as stated, it only affects the background portion.

Thanks!

**Comment by ethanselzer** [comment]
Hi @carlgunderson - Thanks for your comment.  Unfortunately, it is not currently possible to configure an Amazon like lens design. Full control over the lens, along with an Amazon like design option, will be the focus of the next release.

**Comment by ethanselzer** [comment]
@yaser-ali-vp, @carlgunderson - A new lens option has been [released in v2.7.0](https://github.com/ethanselzer/react-image-magnify/releases/tag/v2.7.0). Please have a look and let me know your thoughts. There is [a demo example](https://ethanselzer.github.io/react-image-magnify/#/lens) that includes an optional restyling idea. Thanks for your input!

**Comment by carlgunderson** [comment]
@ethanselzer works like a charm, thanks for implementing this feature!

**Comment by ethanselzer** [comment]
@yaser-ali-vp - There is also an option to provide a custom lens component if you want something completely different.

**Comment by ethanselzer** [comment]
Closing as fixed in [v2.7.0](https://github.com/ethanselzer/react-image-magnify/releases/tag/v2.7.0).
