### ISSUE TITLE
Examples broken for windows, because of pkg-lnk file

### ISSUE THREAD

**Issue by webbertakken** [ethanselzer/react-image-magnify#53]
On Windows the examples folder will not work. The pkg-lnk file is used, which is a linux only file.

I've fixed the issue in PR #52.

**Comment by ethanselzer** [comment]
@webbertakken - Thanks for identifying this issue! I was unaware the example project does not work on Windows. One use case for the example project is as a harness for developing the react-image-magnify package. For convenience in development, the example project imports react-image-magnify locally, instead of from node modules. The example project is built on create-react-app, which does not allow local imports outside the src directory, that is why a symbolic link was used. I'm considering a different approach to importing react-image-magnify locally in the example project. The change is captured on a [branch named 53](https://github.com/ethanselzer/react-image-magnify/tree/53). I'm wondering if you would pull branch 53 and test the example project on Windows. Please let me know.

**Comment by webbertakken** [comment]
Hey @ethanselzer, you're welcome.

Branch 53 seems to works on Windows. You can proceed merging it.

**Comment by ethanselzer** [comment]
Closing as fixed by #54
